CREATE DATABASE leadsDB;

USE leadsDB;

CREATE TABLE User (
  id INT NOT NULL AUTO_INCREMENT,
  username VARCHAR(45) NOT NULL,
  password VARCHAR(45) NOT NULL,
  email VARCHAR(45) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE Team (
id INT NOT NULL AUTO_INCREMENT,
department VARCHAR(45),
 PRIMARY KEY (id)
);

CREATE TABLE Lead (
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(45),
phone VARCHAR(45),
email VARCHAR(45),
opportunity VARCHAR(45),
 PRIMARY KEY (id)
);